# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
cache: packages

r:
  - oldrel
  - release
  - devel

sudo: required

apt_packages:
 - r-cran-rjava

before_cache: Rscript -e 'remotes::install_cran("pkgdown")'
deploy:
  provider: script
  script: Rscript -e 'pkgdown::deploy_site_github()'
  skip_cleanup: true
  on:
    branch: rel
    condition: $TRAVIS_R_VERSION_STRING == "release"

after_success:
  - Rscript -e 'covr::codecov()'
