x-environment: &environment
  MYSQL_DB_LOG: db_log
  NORDICSCIR_DB: db_data
  MYSQL_DB_AUTOREPORT: db_autoreport
  MYSQL_DB_DATA: NoRGastReportDataStaging
  MYSQL_HOST: db
  MYSQL_USER: root
  MYSQL_PASSWORD: root
  FALK_APP_ID: 101
  USERORGID: "pilot"
  SHINYPROXY_USERNAME: test@tester.no
  SHINYPROXY_USERGROUPS: "pilot"
  FALK_USER_EMAIL: kevin.thon@gmail.com


services:

  db:
    image: mysql:8
    restart: "no"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - ./dev/db:/docker-entrypoint-initdb.d
      - ~/softlinks/mysql_db2:/var/lib/mysql
    entrypoint:
      sh -c "/usr/local/bin/docker-entrypoint.sh  --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci"
    ports:
      - 3306:3306

  # app:
  #   depends_on:
  #     - db
  #   image: rapporteket/smerte:main
  #   deploy:
  #     resources:
  #       limits:
  #         memory: 1000M
  #       reservations:
  #         memory: 1000M
  #   ports:
  #     - 3838:3838
  #   volumes:
  #     - ./data-raw/config:/app/R
  #   environment:
  #     R_RAP_CONFIG_PATH: /app/R
  #     FALK_EXTENDED_USER_RIGHTS: "[{\"A\":101,\"R\":\"LU\",\"U\":601225},{\"A\":101,\"R\":\"SC\",\"U\":601225},{\"A\":101,\"R\":\"SC\",\"U\":700922},{\"A\":101,\"R\":\"LU\",\"U\":700922}]"
  #     R_RAP_INSTANCE: "QAC"
  #     << : *environment

  dev:
    depends_on:
      - db
    image: rapporteket/norgast-dev:main
    volumes:
      - ~/.ssh:/home/rstudio/.ssh
      - ~/.gitconfig:/home/rstudio/.gitconfig
      - .:/home/rstudio/smerte
      - ~/softlinks/mydata:/home/rstudio/mydata
      - ../rapbase/.:/home/rstudio/rapbase
    ports:
      - "8787:8787"
    restart: "no"
    environment:
      << : *environment
      DISABLE_AUTH: "true"
      R_RAP_CONFIG_PATH: /home/rstudio/mydata
      FALK_EXTENDED_USER_RIGHTS: "[{\\\"A\\\":101,\\\"R\\\":\\\"LU\\\",\\\"U\\\":601225},{\\\"A\\\":101,\\\"R\\\":\\\"SC\\\",\\\"U\\\":601225},{\\\"A\\\":101,\\\"R\\\":\\\"SC\\\",\\\"U\\\":700922},{\\\"A\\\":101,\\\"R\\\":\\\"LU\\\",\\\"U\\\":700922}]"
      R_RAP_INSTANCE: "QAC"

  adminer:
    depends_on:
      - db
    image: adminer
    restart: "no"
    environment:
      ADMINER_PLUGINS: frames
    ports:
      - 8888:8080
