r:
  raplog:
    archiveDir: logArchive
    eolDays: 730
    target: db
    key: raplog
  autoReport:
    target: db
    key: autoreport
network:
  smtp:
    server:
    port:
  sender:
github:
  organization: Rapporteket
reg:
  smerte:
    nationalAccess:
      reshId: 0
      userRole: SC
      nameKey: Nasjonal
    ousAccess:
      reshId:
      - 705758
      - 705652
      - 4207789
      userRole: LC
      nameKey: 4207789
    databases:
    - name: smerte_nasjonal
      reshId: 0
    - name: smerte_ahus
      reshId: 100089
    - name: smerte_bergen
      reshId: 100082
    - name: smerte_levanger
      reshId: 4214288
    - name: smerte_moreromsdal
      reshId: 4201115
    - name: smerte_ous
      reshId: 4207789
    - name: smerte_ous
      reshId: 705652
    - name: smerte_ous
      reshId: 705758
    - name: smerte_stolavs
      reshId: 100320
    - name: smerte_unn
      reshId: 101719
    - name: smerte_vestreviken
      reshId: 4204083
