---
params:
  title: 'Dekningsgrad ved'
  author: 'Rapporteket'
  hospitalName: 'Ukjent sykehus'
  reshId: 'locallyDefined'
  userRole: 'MyRole'
  startDate: '2017-01-01'
  endDate: '2017-12-31'
  year: '2016'
  tableFormat: 'html'
  registryName: 'rapbase'
  shinySession: list()
title: '`r paste(params$title, params$hospitalName, " i perioden fra ", params$startDate, " til ", params$endDate)`'
author: '`r params$author`'
date: '`r format(Sys.time(), "%d\\. %B, %Y")`'
header-includes:
- \usepackage[english, norsk]{babel}
- \usepackage{booktabs}
- \usepackage{rotating}
---
```{r set options and load packages, include = FALSE}
knitr::opts_chunk$set(echo=FALSE)
options(knitr.table.format = params$tableFormat)
options(tinytex.verbose = TRUE)

# Pakker
library(tidyverse)
library(stringr)
library(zoo)
#library(dplyr)
library(magrittr)
library(lubridate)
library(smerte)
library(knitr)
```

```{r get data, include=FALSE}

if (rapbase::isRapContext()) {
  dat <- getRegDataRapportDekningsgrad(registryName = params$registryName,
                                       reshId = params$reshId,
                                       userRole = params$userRole,
                                       startDate = params$startDate,
                                       endDate = params$endDate,
                                       session = params$shinySession)
} else {
  #Dataimport: skal hente lokale data for hvert sykehus (tar vekk sti, og erstatter med lokal filB)
  path <- read.csv(file = "H:/path.csv", header = FALSE, sep = ";")
  path <- as.data.frame(lapply(path, as.character), stringsAsFactors=FALSE)
  path <- path$V1
  dat <- read.csv(file = path, header = TRUE, sep = ";")
  
  # avdpath <- read.csv(file = "H:/avdelingpath.csv", header = FALSE, sep = ";")
  # avdpath <- as.data.frame(lapply(avdpath, as.character), stringsAsFactors=FALSE)
  # avdpath <- avdpath$V1
  # avd <- read.csv(file = avdpath, header = TRUE, sep = ";", encoding = "UTF-8")
  # #Endrer navn til å matche rapporteket
  # avd <- avd %>% rename(DEPARTMENT_ID = AvdID, DEPARTMENT_NAME = AvdNavn, DEPARTMENT_SHORTNAME = AvdNavnKort)
  # 
  # #Samler datasettene vha InnlAvd i allevarnum og departmentID i avdelingsoversikt
  # dat <- merge(x = dat, y = avd, by.x = c("InnlAvd"), by.y = c("DEPARTMENT_ID"))

  #Må kunne laste inn data for de ulike årene
  #aar <- params$year
  #dat = dat %>% filter(year(date(StartdatoTO)) == aar) #year
}


```

## Dekningsgrad

Dekningsgraden beregnes lokalt for hvert sykehus. Den viser andelen __forløp__ som oppfyller inklusjonskriteriene der pasienter har samtykket til å være med i registeret. 

```{r inkludert, results='asis'}

if (dim(dat)[1] < 1) {
  message <- "I den valgte tidsperioden er det ikke nok data til å angi dekningsgrad."
} else {
  antInk <- sum(dat$InklKritOppf == 1)
  sam <- dat$SkriftligSamtyk
  # NA/NULL to be counted as none-consent
  sam[is.na(sam)] <- 0
  antSam <- sum(sam[sam == 1])
  if (antInk < 1) {
    message <- "I den valgte tidsperioden er det ikke nok data til å angi dekningsgrad."
  } else {
    dekning <- antSam / antInk
    nPatient <- length(unique(dat$PasientID))
    nEvent <- length(unique(dat$ForlopsID))
    nNoConsent <- length(sam[sam == 0])
    nNoIncl <- length(dat$InklKritOppf[dat$InklKritOppf == 0])
    
    patientTxt <- "."
    if (nPatient > 1) {
      patientTxt <- paste(" fordelt på", nPatient, "pasienter.")
    }
    
    if (nPatient == 1) {
      patientTxt <- " for én pasient"
    }
    message <- paste0("Dekningsgraden for ", params$hospitalName,
                      " i den valgte tidsperioden er __",
                      round(dekning, digits = 2), "__. Totalt antall er ",
                      antInk, " hvorav ", antSam, " samtykker er gitt.")
    
    message <- paste0(message, "\n\n### Tallgrunnlag og utvalg  \n",
                      " I utvalget er det ", nEvent, " forløp", patientTxt,
                      " Totalt ", nNoConsent,
                      " forløp mangler samtykke og totalt ", nNoIncl,
                      " forløp oppfyller ikke inklusjonskriteriene.")
  }
  
}

cat(paste("  \n", message))

```
