---
params:
  title: 'NRS'
  author: 'Rapporteket'
  hospitalName: 'Ukjent sykehus'
  reshId: 'locallyDefined'
  userRole: 'MyRole'
  userFullName: 'Ukjent bruker'
  startDate: '2017-01-01'
  endDate: '2017-12-31'
  year: '2016'
  tableFormat: 'html'
  registryName: 'rapbase'
  shinySession: list()
title: '`r paste(params$title, params$hospitalName, " i perioden fra ", params$startDate, " til ", params$endDate)`'
author: '`r params$author`'
date: '`r format(Sys.time(), "%d\\. %B, %Y")`'
reglogo: '`r system.file("www/logoSmerte.png", package = "smerte")`'
regtext: '`r readLines(system.file("registryShortDescription.txt", package = "smerte"))`'
registryName: Smerteregisteret
userFullName: '`r params$userFullName`'
---
```{r set options and load packages, include = FALSE}
knitr::opts_chunk$set(echo=FALSE)
options(knitr.table.format = params$tableFormat)
options(tinytex.verbose = TRUE)
```

```{r get data, include=FALSE}

if (rapbase::isRapContext()) {
  dat <- smerte::getRegDataNRS(registryName = params$registryName,
                                     reshId = params$reshId,
                                     userRole=params$userRole,
                                     startDate = params$startDate,
                                     endDate = params$endDate,
                                     session = params$shinySession)
} else {
  #Dataimport: skal hente lokale data for hvert sykehus (tar vekk sti, og erstatter med lokal fil)
  path <- read.csv(file = "H:/path.csv", header = FALSE, sep = ";")
  path <- as.data.frame(lapply(path, as.character), stringsAsFactors=FALSE)
  path <- path$V1
  dat <- read.csv(file = path, header = TRUE, sep = ";")
}
# 
dat$SykehusNavn[dat$SykehusNavn == "Universitetssykehuset Nord-Norge HF"] = "UNN"
dat$SykehusNavn[dat$SykehusNavn == "St. Olavs Hospital HF"] = "St. Olavs"
dat$SykehusNavn[dat$SykehusNavn == "Oslo universitetssykehus HF"] = "OUS"
dat$SykehusNavn[dat$SykehusNavn == "Helse Bergen HF"] = "HB"
dat$SykehusNavn[dat$SykehusNavn == "Helse Møre og Romsdal HF"] = "HMR"
dat$SykehusNavn[dat$SykehusNavn == "Vestre Viken HF"] = "VV"
dat$SykehusNavn[dat$SykehusNavn == "Akershus universitetssykehus HF"] = "AHUS"

#Legger inn månedene i riktig rekkefølge
dat <- dat %>%
  dplyr::mutate(monthname = zoo::as.Date(zoo::as.yearmon(StartdatoTO)))


#For å evaluere om data er tilstede
dataPresent <- TRUE
if(dim(dat)[1] < 1) {
  dataPresent <- FALSE
}
```


```{r noData, eval=!dataPresent, results='asis'}
cat('# Upps...\nI den valgte tidsperioden er det ikke nok data til å gi 
    ut resultater.')
knitr::knit_exit()

```

# Pasienter som er med i utvalget

Her følger en oversikt over pasientene som er kvalifisert til å være med i dette utvalget (ikke de som hvor "ikke aktuelt" under NRS eller "gitt råd" under tilsyn er huket av for).


```{r datatilpasning, warning = TRUE, message=TRUE, results='asis', eval=dataPresent}

#Lager nye variabler som skal inneholde endring i NRS, settes initielt til NA
dat$stro <- dat$svro <- dat$stbe <- dat$svbe <-  NA
#For de som har svart begge ganger finner vi endring i NRS. 
#Positiv endring = nedgang i smerte, negativ endring = oppgang i smerte. 
#99 er Vet ikke og må også fjernes
for(i in 1:dim(dat)[1]){
  if(!is.na(dat$StSmBev12[i]) & !is.na(dat$StSmBev21[i]) & 
     dat$StSmBev12[i] != 99 & dat$StSmBev21[i] != 99)
  {dat$stbe[i] <- dat$StSmBev12[i] - dat$StSmBev21[i]}
  if(!is.na(dat$SvSmBev12[i]) & !is.na(dat$SvSmBev21[i]) &
     dat$SvSmBev12[i] != 99 & dat$SvSmBev21[i] != 99)
  {dat$svbe[i] <- dat$SvSmBev12[i] - dat$SvSmBev21[i]}
  if(!is.na(dat$StSmRo12[i]) & !is.na(dat$StSmRo21[i]) &
     dat$StSmRo12[i] != 99 & dat$StSmRo21[i] != 99)
  {dat$stro[i] <- dat$StSmRo12[i] - dat$StSmRo21[i]}
  if(!is.na(dat$SvSmRo12[i]) & !is.na(dat$SvSmRo21[i]) &
     dat$SvSmRo12[i] != 99 & dat$SvSmRo21[i] != 99)
  {dat$svro[i] <- dat$SvSmRo12[i] - dat$SvSmRo21[i]}
}
  
#De som er NA må få en meningsfullverdi til tabellen som skal skrives
dat$stbe = dat %>% dplyr::mutate(stbe = ifelse(is.na(stbe), "Mangler", stbe))
dat$svbe = dat %>% dplyr::mutate(svbe = ifelse(is.na(svbe), "Mangler", svbe))
dat$stro = dat %>% dplyr::mutate(stro = ifelse(is.na(stro), "Mangler", stro))
dat$svro = dat %>% dplyr::mutate(svro = ifelse(is.na(svro), "Mangler", svro))

dattest <- dat[dat$Tilsett == 1 & dat$AngiNRS12 != 2 & dat$AngiNRS21 != 2, ]
```

```{r generelt, warning = FALSE, message=FALSE, results='asis'}

oversikt <- dattest %>%
    dplyr::group_by(SykehusNavn, Tilsett) %>%
    dplyr::summarise(n = dplyr::n()) %>%
    dply::mutate( ant = sum(n), freq = n/sum(n)) %>%
    #dplyr::filter(henvtils == 1)
 oversikt 
  # #Tar bort kolonne for behtils oppfylt
  # kvalind2 <- kvalind2 %>%
  #   dplyr::select(SykehusNavn, n, ant, freq)
  # 
  # #Tabell
  # rapbase::mst(
  #   tab = kvalind2,
  #   col_names = c("Sykehus", "Antall", "Totalt antall", "Andel"),
  #   type = params$tableFormat,
  #   cap = paste0("Oversikt over andel pasienter som ble tilsett samme dag som de ble henvist."),
  #   digs = 2,
  #   align = c("l", "r", "r", "r"))
```
