SET NAMES utf8;
SET time_zone = '+00:00';
SET foreign_key_checks = 0;
SET sql_mode = 'NO_AUTO_VALUE_ON_ZERO';

DROP TABLE IF EXISTS `allevar`;
CREATE TABLE `allevar` (
  `PasientID` int(10) unsigned DEFAULT NULL,
  `AvdRESH` varchar(30) COLLATE utf8_danish_ci DEFAULT NULL,
  `SykehusNavn` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `ForlopsID` int(9) NOT NULL,
  `RegDato11` date DEFAULT NULL,
  `Lokasjon` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `InnlAvd` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `InnlDiag` varchar(200) COLLATE utf8_danish_ci DEFAULT NULL,
  `InnlDiagVersj` int(10) unsigned DEFAULT NULL,
  `AkuttLang` tinyint(3) DEFAULT NULL,
  `Ingen4a` varchar(5) COLLATE utf8_danish_ci DEFAULT NULL,
  `NonOpioid4a` varchar(5) COLLATE utf8_danish_ci DEFAULT NULL,
  `Opioid4a` varchar(5) COLLATE utf8_danish_ci DEFAULT NULL,
  `Benzo4a` varchar(5) COLLATE utf8_danish_ci DEFAULT NULL,
  `KoAnalg4a` varchar(5) COLLATE utf8_danish_ci DEFAULT NULL,
  `Vetikke4a` varchar(5) COLLATE utf8_danish_ci DEFAULT NULL,
  `Ingen4b` varchar(5) COLLATE utf8_danish_ci DEFAULT NULL,
  `NonOpioid4b` varchar(5) COLLATE utf8_danish_ci DEFAULT NULL,
  `Opioid4b` varchar(5) COLLATE utf8_danish_ci DEFAULT NULL,
  `Benzo4b` varchar(5) COLLATE utf8_danish_ci DEFAULT NULL,
  `KoAnalg4b` varchar(5) COLLATE utf8_danish_ci DEFAULT NULL,
  `Vetikke4b` varchar(5) COLLATE utf8_danish_ci DEFAULT NULL,
  `DDMoTbl` decimal(5,1) DEFAULT NULL,
  `OMEQMoTbl` decimal(6,1) DEFAULT NULL,
  `DDMoDep` decimal(5,1) DEFAULT NULL,
  `OMEQMoDep` decimal(6,1) DEFAULT NULL,
  `DDMoIv` decimal(5,1) DEFAULT NULL,
  `OMEQMoIv` decimal(6,1) DEFAULT NULL,
  `DDOxKps` decimal(5,1) DEFAULT NULL,
  `OMEQOxKps` decimal(6,1) DEFAULT NULL,
  `DDOxDep` decimal(5,1) DEFAULT NULL,
  `OMEQOxDep` decimal(6,1) DEFAULT NULL,
  `DDOxIv` decimal(5,1) DEFAULT NULL,
  `OMEQOxIv` decimal(6,1) DEFAULT NULL,
  `DDBuPl` decimal(5,1) DEFAULT NULL,
  `OMEQBuPl` decimal(7,1) DEFAULT NULL,
  `DDBuTbl` decimal(5,1) DEFAULT NULL,
  `OMEQBuTbl` decimal(7,1) DEFAULT NULL,
  `DDFePl` decimal(5,1) DEFAULT NULL,
  `OMEQFePl` decimal(7,1) DEFAULT NULL,
  `DDFeTblSpray` decimal(5,1) DEFAULT NULL,
  `OMEQFeTblSpray` decimal(7,1) DEFAULT NULL,
  `DDHyKps` decimal(5,1) DEFAULT NULL,
  `OMEQHyKps` decimal(7,1) DEFAULT NULL,
  `DDHyDepKps` decimal(5,1) DEFAULT NULL,
  `OMEQHyDepKps` decimal(7,1) DEFAULT NULL,
  `DDHyIv` decimal(5,1) DEFAULT NULL,
  `OMEQHyIv` decimal(7,1) DEFAULT NULL,
  `DDKeIv` decimal(5,1) DEFAULT NULL,
  `OMEQKeIv` decimal(7,1) DEFAULT NULL,
  `DDKeTbl` decimal(5,1) DEFAULT NULL,
  `OMEQKeTbl` decimal(7,1) DEFAULT NULL,
  `DDPeSupp` decimal(5,1) DEFAULT NULL,
  `OMEQPeSupp` decimal(7,1) DEFAULT NULL,
  `DDPeIM` decimal(5,1) DEFAULT NULL,
  `OMEQPeIM` decimal(7,1) DEFAULT NULL,
  `DDCoTbl` decimal(5,1) DEFAULT NULL,
  `OMEQCoTbl` decimal(7,1) DEFAULT NULL,
  `DDTrKps` decimal(5,1) DEFAULT NULL,
  `OMEQTrKps` decimal(7,1) DEFAULT NULL,
  `DDTrDepTbl` decimal(5,1) DEFAULT NULL,
  `OMEQTrDepTbl` decimal(7,1) DEFAULT NULL,
  `DDTaDepTbl` decimal(5,1) DEFAULT NULL,
  `OMEQTaDepTbl` decimal(7,1) DEFAULT NULL,
  `DDMetLav` decimal(3,1) DEFAULT NULL,
  `OMEQMetLav` decimal(7,1) DEFAULT NULL,
  `DDMetHoy` decimal(4,1) DEFAULT NULL,
  `OMEQMetHoy` decimal(7,1) DEFAULT NULL,
  `MoEkvivalens` decimal(10,1) DEFAULT NULL,
  `UhenBrukMed` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `SentralBlokkB11` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `EDAB11` varchar(5) COLLATE utf8_danish_ci DEFAULT NULL,
  `SAB11` varchar(5) COLLATE utf8_danish_ci DEFAULT NULL,
  `Opbehd` varchar(5) COLLATE utf8_danish_ci DEFAULT NULL,
  `LAbehd` varchar(5) COLLATE utf8_danish_ci DEFAULT NULL,
  `KoAbedel` varchar(5) COLLATE utf8_danish_ci DEFAULT NULL,
  `Annetbehd` varchar(5) COLLATE utf8_danish_ci DEFAULT NULL,
  `PeriferBlokkB11` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `PlBrachBlokB11` varchar(5) COLLATE utf8_danish_ci DEFAULT NULL,
  `InterscB11` varchar(5) COLLATE utf8_danish_ci DEFAULT NULL,
  `SupraclavB11` varchar(5) COLLATE utf8_danish_ci DEFAULT NULL,
  `InfraclavB11` varchar(5) COLLATE utf8_danish_ci DEFAULT NULL,
  `AxilB11` varchar(5) COLLATE utf8_danish_ci DEFAULT NULL,
  `PVBB11` varchar(5) COLLATE utf8_danish_ci DEFAULT NULL,
  `ICBB11` varchar(5) COLLATE utf8_danish_ci DEFAULT NULL,
  `PECSB11` varchar(5) COLLATE utf8_danish_ci DEFAULT NULL,
  `PECSUnderkat1B11` varchar(5) COLLATE utf8_danish_ci DEFAULT NULL,
  `PECSUnderkat2B11` varchar(5) COLLATE utf8_danish_ci DEFAULT NULL,
  `TAPB11` varchar(5) COLLATE utf8_danish_ci DEFAULT NULL,
  `FemblokB11` varchar(5) COLLATE utf8_danish_ci DEFAULT NULL,
  `AdKanalblokB11` varchar(5) COLLATE utf8_danish_ci DEFAULT NULL,
  `IschiasblokB11` varchar(5) COLLATE utf8_danish_ci DEFAULT NULL,
  `SubglutB11` varchar(5) COLLATE utf8_danish_ci DEFAULT NULL,
  `PopliteaB11` varchar(5) COLLATE utf8_danish_ci DEFAULT NULL,
  `PLBB11` varchar(5) COLLATE utf8_danish_ci DEFAULT NULL,
  `FICBB11` varchar(5) COLLATE utf8_danish_ci DEFAULT NULL,
  `SPBB11` varchar(5) COLLATE utf8_danish_ci DEFAULT NULL,
  `AnnenBlokB11` varchar(5) COLLATE utf8_danish_ci DEFAULT NULL,
  `SShotB11` varchar(5) COLLATE utf8_danish_ci DEFAULT NULL,
  `InfusjonB11` varchar(5) COLLATE utf8_danish_ci DEFAULT NULL,
  `TidligereRus` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `PaagaaRus` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `LAR` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `AvdRegSmIntensSD` tinyint(3) DEFAULT NULL,
  `AvdRegSmIntensSDMangler` varchar(5) COLLATE utf8_danish_ci DEFAULT NULL,
  `Regdato12` date DEFAULT NULL,
  `AngiNRS12` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `StSmRo12` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `SvSmRo12` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `StSmBev12` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `SvSmBev12` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `Regdato21` date DEFAULT NULL,
  `AngiNRS21` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `StSmRo21` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `SvSmRo21` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `StSmBev21` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `SvSmBev21` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `SluttDato` date DEFAULT NULL,
  `Lege` varchar(5) COLLATE utf8_danish_ci DEFAULT NULL,
  `AntTilsLege` smallint(6) DEFAULT NULL,
  `KonfLege` varchar(5) COLLATE utf8_danish_ci DEFAULT NULL,
  `AntTilsKonfLege` smallint(6) DEFAULT NULL,
  `SykPleier` varchar(5) COLLATE utf8_danish_ci DEFAULT NULL,
  `AntTilsSykPleier` smallint(6) DEFAULT NULL,
  `FysioT` varchar(5) COLLATE utf8_danish_ci DEFAULT NULL,
  `AntTilsFysioT` smallint(6) DEFAULT NULL,
  `Psyk` varchar(5) COLLATE utf8_danish_ci DEFAULT NULL,
  `AntTilsPsyk` smallint(6) DEFAULT NULL,
  `Sosio` varchar(5) COLLATE utf8_danish_ci DEFAULT NULL,
  `AntTilsSosio` smallint(6) DEFAULT NULL,
  `AmbLege` varchar(5) COLLATE utf8_danish_ci DEFAULT NULL,
  `AntTilsAmbLege` smallint(6) DEFAULT NULL,
  `AmbSykepleier` varchar(5) COLLATE utf8_danish_ci DEFAULT NULL,
  `AntTilsAmbSpl` smallint(6) DEFAULT NULL,
  `AntPasTils` tinyint(3) DEFAULT NULL,
  `TotTid` smallint(6) DEFAULT NULL,
  `MedBeh22` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `Ingen1a` varchar(5) COLLATE utf8_danish_ci DEFAULT NULL,
  `O2beh` varchar(5) COLLATE utf8_danish_ci DEFAULT NULL,
  `Motgift1a` varchar(5) COLLATE utf8_danish_ci DEFAULT NULL,
  `ForstOvervaakn` varchar(5) COLLATE utf8_danish_ci DEFAULT NULL,
  `IntensivBeh` varchar(5) COLLATE utf8_danish_ci DEFAULT NULL,
  `Resuc` varchar(5) COLLATE utf8_danish_ci DEFAULT NULL,
  `RespiratorBeh` varchar(5) COLLATE utf8_danish_ci DEFAULT NULL,
  `IkkeMedBeh` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `PSBeh` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `FysioBeh` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `AnnenIkkeMedBeh` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `SentralBlokk` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `EDA` varchar(5) COLLATE utf8_danish_ci DEFAULT NULL,
  `SA` varchar(5) COLLATE utf8_danish_ci DEFAULT NULL,
  `Opbehd221d` varchar(5) COLLATE utf8_danish_ci DEFAULT NULL,
  `LAbehd221d` varchar(5) COLLATE utf8_danish_ci DEFAULT NULL,
  `KoAbedel221d` varchar(5) COLLATE utf8_danish_ci DEFAULT NULL,
  `Annetbehd221d` varchar(5) COLLATE utf8_danish_ci DEFAULT NULL,
  `Kompl1d` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `ISEDHematom` varchar(5) COLLATE utf8_danish_ci DEFAULT NULL,
  `Meningitt` varchar(5) COLLATE utf8_danish_ci DEFAULT NULL,
  `EDabsc` varchar(5) COLLATE utf8_danish_ci DEFAULT NULL,
  `NervSkad1d` varchar(5) COLLATE utf8_danish_ci DEFAULT NULL,
  `MigKat` varchar(5) COLLATE utf8_danish_ci DEFAULT NULL,
  `IvinjLA` varchar(5) COLLATE utf8_danish_ci DEFAULT NULL,
  `PShodepine` varchar(5) COLLATE utf8_danish_ci DEFAULT NULL,
  `FallpgaLA` varchar(5) COLLATE utf8_danish_ci DEFAULT NULL,
  `LekCSF` varchar(5) COLLATE utf8_danish_ci DEFAULT NULL,
  `Ingen1d` varchar(5) COLLATE utf8_danish_ci DEFAULT NULL,
  `Operasjon1d` varchar(5) COLLATE utf8_danish_ci DEFAULT NULL,
  `AbBeh1d` varchar(5) COLLATE utf8_danish_ci DEFAULT NULL,
  `FjernKat1d` varchar(5) COLLATE utf8_danish_ci DEFAULT NULL,
  `Bloodpatch` varchar(5) COLLATE utf8_danish_ci DEFAULT NULL,
  `Sengeleie` varchar(5) COLLATE utf8_danish_ci DEFAULT NULL,
  `FzKoff` varchar(5) COLLATE utf8_danish_ci DEFAULT NULL,
  `EndrMed` varchar(5) COLLATE utf8_danish_ci DEFAULT NULL,
  `PeriferBlokk` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `PlBrachBlok` varchar(5) COLLATE utf8_danish_ci DEFAULT NULL,
  `Intersc` varchar(5) COLLATE utf8_danish_ci DEFAULT NULL,
  `Supraclav` varchar(5) COLLATE utf8_danish_ci DEFAULT NULL,
  `Infraklav` varchar(5) COLLATE utf8_danish_ci DEFAULT NULL,
  `Axil` varchar(5) COLLATE utf8_danish_ci DEFAULT NULL,
  `PVB` varchar(5) COLLATE utf8_danish_ci DEFAULT NULL,
  `ICB` varchar(5) COLLATE utf8_danish_ci DEFAULT NULL,
  `PECS` varchar(5) COLLATE utf8_danish_ci DEFAULT NULL,
  `Underkat1` varchar(5) COLLATE utf8_danish_ci DEFAULT NULL,
  `Underkat2` varchar(5) COLLATE utf8_danish_ci DEFAULT NULL,
  `TAP` varchar(5) COLLATE utf8_danish_ci DEFAULT NULL,
  `Femblok` varchar(5) COLLATE utf8_danish_ci DEFAULT NULL,
  `AdKanalblok` varchar(5) COLLATE utf8_danish_ci DEFAULT NULL,
  `Ischiasblok` varchar(5) COLLATE utf8_danish_ci DEFAULT NULL,
  `Subglut` varchar(5) COLLATE utf8_danish_ci DEFAULT NULL,
  `Popliteal` varchar(5) COLLATE utf8_danish_ci DEFAULT NULL,
  `PLB` varchar(5) COLLATE utf8_danish_ci DEFAULT NULL,
  `FICB` varchar(5) COLLATE utf8_danish_ci DEFAULT NULL,
  `SPB` varchar(5) COLLATE utf8_danish_ci DEFAULT NULL,
  `AnnenBlok` varchar(5) COLLATE utf8_danish_ci DEFAULT NULL,
  `SShot` varchar(5) COLLATE utf8_danish_ci DEFAULT NULL,
  `Infusjon` varchar(5) COLLATE utf8_danish_ci DEFAULT NULL,
  `Kompl1e` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `NervSkad1e` varchar(5) COLLATE utf8_danish_ci DEFAULT NULL,
  `Infeksjon1e` varchar(5) COLLATE utf8_danish_ci DEFAULT NULL,
  `IvInjLA1e` varchar(5) COLLATE utf8_danish_ci DEFAULT NULL,
  `Intox1e` varchar(5) COLLATE utf8_danish_ci DEFAULT NULL,
  `Ingen1e` varchar(5) COLLATE utf8_danish_ci DEFAULT NULL,
  `Op1e` varchar(5) COLLATE utf8_danish_ci DEFAULT NULL,
  `AbBeh1e` varchar(5) COLLATE utf8_danish_ci DEFAULT NULL,
  `FjernKat1e` varchar(5) COLLATE utf8_danish_ci DEFAULT NULL,
  `EndretMedInt1e` varchar(5) COLLATE utf8_danish_ci DEFAULT NULL,
  `VidereOppf` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `OppfanneInst` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `BehNedtrappAvsluttTils` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `Journalnotat` varchar(5) COLLATE utf8_danish_ci DEFAULT NULL,
  `PlanLevertPas` varchar(5) COLLATE utf8_danish_ci DEFAULT NULL,
  `UtdeltOpioidbrosjyre` varchar(5) COLLATE utf8_danish_ci DEFAULT NULL,
  `OppfolgAvdeling` varchar(5) COLLATE utf8_danish_ci DEFAULT NULL,
  `AarsakVedNei` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `KontFastlege` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `OppfSmeKl` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `FerdigSkjema22` varchar(5) COLLATE utf8_danish_ci DEFAULT NULL,
  `Op22` varchar(5) COLLATE utf8_danish_ci DEFAULT NULL,
  `NOp22` varchar(5) COLLATE utf8_danish_ci DEFAULT NULL,
  `KoAn22` varchar(5) COLLATE utf8_danish_ci DEFAULT NULL,
  `Bzd22` varchar(5) COLLATE utf8_danish_ci DEFAULT NULL,
  `DDMoTbl22` decimal(5,1) DEFAULT NULL,
  `OMEQMoTbl22` decimal(6,1) DEFAULT NULL,
  `DDMoDep22` decimal(5,1) DEFAULT NULL,
  `OMEQMoDep22` decimal(6,1) DEFAULT NULL,
  `DDMoIV22` decimal(5,1) DEFAULT NULL,
  `OMEQMoIV22` decimal(6,1) DEFAULT NULL,
  `DDOxKps22` decimal(5,1) DEFAULT NULL,
  `OMEQOxKps22` decimal(6,1) DEFAULT NULL,
  `DDOxDep22` decimal(5,1) DEFAULT NULL,
  `OMEQOxDep22` decimal(6,1) DEFAULT NULL,
  `DDOxIV22` decimal(5,1) DEFAULT NULL,
  `OMEQOxIV22` decimal(6,1) DEFAULT NULL,
  `DDBuPl22` decimal(5,1) DEFAULT NULL,
  `OMEQBuPl22` decimal(7,1) DEFAULT NULL,
  `DDBuTbl22` decimal(5,1) DEFAULT NULL,
  `OMEQBuTbl22` decimal(7,1) DEFAULT NULL,
  `DDFePl22` decimal(5,1) DEFAULT NULL,
  `OMEQFePl22` decimal(7,1) DEFAULT NULL,
  `DDFeTblSpray22` decimal(5,1) DEFAULT NULL,
  `OMEQFeTblSpray22` decimal(7,1) DEFAULT NULL,
  `DDHyKps22` decimal(5,1) DEFAULT NULL,
  `OMEQHyKps22` decimal(7,1) DEFAULT NULL,
  `DDHyDepKps22` decimal(5,1) DEFAULT NULL,
  `OMEQHyDepKps22` decimal(7,1) DEFAULT NULL,
  `DDHyIv22` decimal(5,1) DEFAULT NULL,
  `OMEQHyIv22` decimal(7,1) DEFAULT NULL,
  `DDKeIV22` decimal(5,1) DEFAULT NULL,
  `OMEQKeIV22` decimal(7,1) DEFAULT NULL,
  `DDKeTbl22` decimal(5,1) DEFAULT NULL,
  `OMEQKeTbl22` decimal(7,1) DEFAULT NULL,
  `DDPeSupp22` decimal(5,1) DEFAULT NULL,
  `OMEQPeSupp22` decimal(7,1) DEFAULT NULL,
  `DDPeIM22` decimal(5,1) DEFAULT NULL,
  `OMEQPeIM22` decimal(7,1) DEFAULT NULL,
  `DDCoTbl22` decimal(5,1) DEFAULT NULL,
  `OMEQCoTbl22` decimal(7,1) DEFAULT NULL,
  `DDTrKps22` decimal(5,1) DEFAULT NULL,
  `OMEQTrKps22` decimal(7,1) DEFAULT NULL,
  `DDTrDepTbl22` decimal(5,1) DEFAULT NULL,
  `OMEQTrDepTbl22` decimal(7,1) DEFAULT NULL,
  `DDTaDepTbl22` decimal(5,1) DEFAULT NULL,
  `OMEQTaDepTbl22` decimal(7,1) DEFAULT NULL,
  `DDMetLav22` decimal(3,1) DEFAULT NULL,
  `OMEQMetLav22` decimal(7,1) DEFAULT NULL,
  `DDMetHoy22` decimal(4,1) DEFAULT NULL,
  `OMEQMetHoy22` decimal(7,1) DEFAULT NULL,
  `MoEkvivalens22` decimal(10,1) DEFAULT NULL,
  `AlvRespDepr` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `DatoUtfHADS` date DEFAULT NULL,
  `PasDelUtf` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `GrManglUtfylHADS` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `HADSSpm1` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `HADSSpm2` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `HADSSpm3` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `HADSSpm4` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `HADSSpm5` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `HADSSpm6` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `HADSSpm7` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `HADSSpm8` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `HADSSpm9` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `HADSSpm10` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `HADSSpm11` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `HADSSpm12` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `HADSSpm13` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `HADSSpm14` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `HADSScoreDepresjon` tinyint(3) DEFAULT NULL,
  `HADSScoreAngst` tinyint(3) DEFAULT NULL,
  `HenvistDato` date DEFAULT NULL,
  `Tilsynsanmodnin` varchar(5) COLLATE utf8_danish_ci DEFAULT NULL,
  `TelefonCalling` varchar(5) COLLATE utf8_danish_ci DEFAULT NULL,
  `StartdatoTO` date DEFAULT NULL,
  `Tilsett` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `Norsktalende` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `alder` smallint(6) DEFAULT NULL,
  `KognSvekket` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `InklKritOppf` tinyint(3) DEFAULT NULL,
  `SkriftligSamtyk` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `TypeManglSamt` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `DatoSamtykke` date DEFAULT NULL,
  `DatotrekSamt` date DEFAULT NULL,
  `DatoUtfylOpioid` date DEFAULT NULL,
  `PasdelUtfylOpioid` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `AarsakmanglUtfylOpioid` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `Utskrevetsykehus` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `Smstilletterutskrivelse` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `DolcontinMalfin` varchar(5) COLLATE utf8_danish_ci DEFAULT NULL,
  `FentanylplDurogesicpl` varchar(5) COLLATE utf8_danish_ci DEFAULT NULL,
  `Metadon` varchar(5) COLLATE utf8_danish_ci DEFAULT NULL,
  `Morfin` varchar(5) COLLATE utf8_danish_ci DEFAULT NULL,
  `Norspanplaster` varchar(5) COLLATE utf8_danish_ci DEFAULT NULL,
  `OxyxontinReltebon` varchar(5) COLLATE utf8_danish_ci DEFAULT NULL,
  `OxynormOxykodon` varchar(5) COLLATE utf8_danish_ci DEFAULT NULL,
  `Palexia` varchar(5) COLLATE utf8_danish_ci DEFAULT NULL,
  `PalladonHydromorfon` varchar(5) COLLATE utf8_danish_ci DEFAULT NULL,
  `Paralginforte` varchar(5) COLLATE utf8_danish_ci DEFAULT NULL,
  `Buprenorfin` varchar(5) COLLATE utf8_danish_ci DEFAULT NULL,
  `Targiniq` varchar(5) COLLATE utf8_danish_ci DEFAULT NULL,
  `Tramadolvarianter` varchar(5) COLLATE utf8_danish_ci DEFAULT NULL,
  `Andre` varchar(5) COLLATE utf8_danish_ci DEFAULT NULL,
  `Usikker` varchar(5) COLLATE utf8_danish_ci DEFAULT NULL,
  `Fortsattbruk` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `InfoNedtrapping` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `HvemInfoNedtrapping` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `MuntligInfoNedtrapp` varchar(5) COLLATE utf8_danish_ci DEFAULT NULL,
  `SkriftligNedtrappingsplan` varchar(5) COLLATE utf8_danish_ci DEFAULT NULL,
  `InfoBrosjyreNedtrapp` varchar(5) COLLATE utf8_danish_ci DEFAULT NULL,
  `FolgeAnbefalingNedtrapp` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `OpplevdAbstinenssympt` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `ForstodAbstinenssympt` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `LosningProblemAbstinens` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `OpplevdPlagsomTretthet` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `LosningProblemTretthet` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `InfoSmertestillBilkjoring` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `HvemInfoSmertestillBilkjoring` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `MuntligInfoBilkjoring` varchar(5) COLLATE utf8_danish_ci DEFAULT NULL,
  `SkriftigInfoBilkjoring` varchar(5) COLLATE utf8_danish_ci DEFAULT NULL,
  `InfoBrosyjreBilkjoring` varchar(5) COLLATE utf8_danish_ci DEFAULT NULL,
  `HenvendelseAngSmertestill` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `InfoBrukNedtrapp` varchar(5) COLLATE utf8_danish_ci DEFAULT NULL,
  `InfoSmstillBilkjoring` varchar(5) COLLATE utf8_danish_ci DEFAULT NULL,
  `InfoAbstinenser` varchar(5) COLLATE utf8_danish_ci DEFAULT NULL,
  `InfoBivirkninger` varchar(5) COLLATE utf8_danish_ci DEFAULT NULL,
  `TettOppfolging` varchar(5) COLLATE utf8_danish_ci DEFAULT NULL,
  `DatoinhOppl` date DEFAULT NULL,
  `Fdato` date DEFAULT NULL,
  `Kjonn` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `SkrSamtykke` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `DatoinhSamt` date DEFAULT NULL,
  `ManglSamt` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `DatoTrektSamt` date DEFAULT NULL,
  `Avdod` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `Ddato` date DEFAULT NULL,
  `Adrtype` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `DatoUfylEval` date DEFAULT NULL,
  `PasdelUtfylEval` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `AarsakmanglUfylEval` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `HuskerSmerteteam` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `EvalSpm1` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `EvalSpm2` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `EvalSpm3` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `EvalSpm4` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `EvalSpm5` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `EvalSpm6` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `EvalSpm7` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `EvalSpm8` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `EvalSpm9` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `EvalSpm10` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `EvalSpm11` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `DatoUfylPR` date DEFAULT NULL,
  `PasDelUfylPR` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `GrunnManglUtfyl` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `PRSpm1` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `PRSpm2` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `PRSpm3` tinyint(3) DEFAULT NULL,
  `PRSpm3Mangler` varchar(5) COLLATE utf8_danish_ci DEFAULT NULL,
  `PRSpm4` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `PRSpm5` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `PRSpm6` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  PRIMARY KEY (`ForlopsID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_danish_ci;


DROP TABLE IF EXISTS `allevarnum`;
CREATE TABLE `allevarnum` (
  `PasientID` int(10) unsigned DEFAULT NULL,
  `AvdRESH` varchar(30) COLLATE utf8_danish_ci DEFAULT NULL,
  `SykehusNavn` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `ForlopsID` int(9) NOT NULL,
  `RegDato11` date DEFAULT NULL,
  `Lokasjon` int(10) unsigned DEFAULT NULL,
  `InnlAvd` int(10) unsigned DEFAULT NULL,
  `InnlDiag` varchar(200) COLLATE utf8_danish_ci DEFAULT NULL,
  `InnlDiagVersj` int(10) unsigned DEFAULT NULL,
  `AkuttLang` tinyint(3) DEFAULT NULL,
  `Ingen4a` tinyint(3) DEFAULT NULL,
  `NonOpioid4a` tinyint(3) DEFAULT NULL,
  `Opioid4a` tinyint(3) DEFAULT NULL,
  `Benzo4a` tinyint(3) DEFAULT NULL,
  `KoAnalg4a` tinyint(3) DEFAULT NULL,
  `Vetikke4a` tinyint(3) DEFAULT NULL,
  `Ingen4b` tinyint(3) DEFAULT NULL,
  `NonOpioid4b` tinyint(3) DEFAULT NULL,
  `Opioid4b` tinyint(3) DEFAULT NULL,
  `Benzo4b` tinyint(3) DEFAULT NULL,
  `KoAnalg4b` tinyint(3) DEFAULT NULL,
  `Vetikke4b` tinyint(3) DEFAULT NULL,
  `DDMoTbl` decimal(5,1) DEFAULT NULL,
  `OMEQMoTbl` decimal(6,1) DEFAULT NULL,
  `DDMoDep` decimal(5,1) DEFAULT NULL,
  `OMEQMoDep` decimal(6,1) DEFAULT NULL,
  `DDMoIv` decimal(5,1) DEFAULT NULL,
  `OMEQMoIv` decimal(6,1) DEFAULT NULL,
  `DDOxKps` decimal(5,1) DEFAULT NULL,
  `OMEQOxKps` decimal(6,1) DEFAULT NULL,
  `DDOxDep` decimal(5,1) DEFAULT NULL,
  `OMEQOxDep` decimal(6,1) DEFAULT NULL,
  `DDOxIv` decimal(5,1) DEFAULT NULL,
  `OMEQOxIv` decimal(6,1) DEFAULT NULL,
  `DDBuPl` decimal(5,1) DEFAULT NULL,
  `OMEQBuPl` decimal(7,1) DEFAULT NULL,
  `DDBuTbl` decimal(5,1) DEFAULT NULL,
  `OMEQBuTbl` decimal(7,1) DEFAULT NULL,
  `DDFePl` decimal(5,1) DEFAULT NULL,
  `OMEQFePl` decimal(7,1) DEFAULT NULL,
  `DDFeTblSpray` decimal(5,1) DEFAULT NULL,
  `OMEQFeTblSpray` decimal(7,1) DEFAULT NULL,
  `DDHyKps` decimal(5,1) DEFAULT NULL,
  `OMEQHyKps` decimal(7,1) DEFAULT NULL,
  `DDHyDepKps` decimal(5,1) DEFAULT NULL,
  `OMEQHyDepKps` decimal(7,1) DEFAULT NULL,
  `DDHyIv` decimal(5,1) DEFAULT NULL,
  `OMEQHyIv` decimal(7,1) DEFAULT NULL,
  `DDKeIv` decimal(5,1) DEFAULT NULL,
  `OMEQKeIv` decimal(7,1) DEFAULT NULL,
  `DDKeTbl` decimal(5,1) DEFAULT NULL,
  `OMEQKeTbl` decimal(7,1) DEFAULT NULL,
  `DDPeSupp` decimal(5,1) DEFAULT NULL,
  `OMEQPeSupp` decimal(7,1) DEFAULT NULL,
  `DDPeIM` decimal(5,1) DEFAULT NULL,
  `OMEQPeIM` decimal(7,1) DEFAULT NULL,
  `DDCoTbl` decimal(5,1) DEFAULT NULL,
  `OMEQCoTbl` decimal(7,1) DEFAULT NULL,
  `DDTrKps` decimal(5,1) DEFAULT NULL,
  `OMEQTrKps` decimal(7,1) DEFAULT NULL,
  `DDTrDepTbl` decimal(5,1) DEFAULT NULL,
  `OMEQTrDepTbl` decimal(7,1) DEFAULT NULL,
  `DDTaDepTbl` decimal(5,1) DEFAULT NULL,
  `OMEQTaDepTbl` decimal(7,1) DEFAULT NULL,
  `DDMetLav` decimal(3,1) DEFAULT NULL,
  `OMEQMetLav` decimal(7,1) DEFAULT NULL,
  `DDMetHoy` decimal(4,1) DEFAULT NULL,
  `OMEQMetHoy` decimal(7,1) DEFAULT NULL,
  `MoEkvivalens` decimal(10,1) DEFAULT NULL,
  `UhenBrukMed` tinyint(3) DEFAULT NULL,
  `SentralBlokkB11` tinyint(3) DEFAULT NULL,
  `EDAB11` tinyint(3) DEFAULT NULL,
  `SAB11` tinyint(3) DEFAULT NULL,
  `Opbehd` tinyint(3) DEFAULT NULL,
  `LAbehd` tinyint(3) DEFAULT NULL,
  `KoAbedel` tinyint(3) DEFAULT NULL,
  `Annetbehd` tinyint(3) DEFAULT NULL,
  `PeriferBlokkB11` tinyint(3) DEFAULT NULL,
  `PlBrachBlokB11` tinyint(3) DEFAULT NULL,
  `InterscB11` tinyint(3) DEFAULT NULL,
  `SupraclavB11` tinyint(3) DEFAULT NULL,
  `InfraclavB11` tinyint(3) DEFAULT NULL,
  `AxilB11` tinyint(3) DEFAULT NULL,
  `PVBB11` tinyint(3) DEFAULT NULL,
  `ICBB11` tinyint(3) DEFAULT NULL,
  `PECSB11` tinyint(3) DEFAULT NULL,
  `PECSUnderkat1B11` tinyint(3) DEFAULT NULL,
  `PECSUnderkat2B11` tinyint(3) DEFAULT NULL,
  `TAPB11` tinyint(3) DEFAULT NULL,
  `FemblokB11` tinyint(3) DEFAULT NULL,
  `AdKanalblokB11` tinyint(3) DEFAULT NULL,
  `IschiasblokB11` tinyint(3) DEFAULT NULL,
  `SubglutB11` tinyint(3) DEFAULT NULL,
  `PopliteaB11` tinyint(3) DEFAULT NULL,
  `PLBB11` tinyint(3) DEFAULT NULL,
  `FICBB11` tinyint(3) DEFAULT NULL,
  `SPBB11` tinyint(3) DEFAULT NULL,
  `AnnenBlokB11` tinyint(3) DEFAULT NULL,
  `SShotB11` tinyint(3) DEFAULT NULL,
  `InfusjonB11` tinyint(3) DEFAULT NULL,
  `TidligereRus` tinyint(3) DEFAULT NULL,
  `PaagaaRus` tinyint(3) DEFAULT NULL,
  `LAR` tinyint(3) DEFAULT NULL,
  `AvdRegSmIntensSD` tinyint(3) DEFAULT NULL,
  `AvdRegSmIntensSDMangler` tinyint(3) DEFAULT NULL,
  `Regdato12` date DEFAULT NULL,
  `AngiNRS12` tinyint(3) DEFAULT NULL,
  `StSmRo12` tinyint(3) DEFAULT NULL,
  `SvSmRo12` tinyint(3) DEFAULT NULL,
  `StSmBev12` tinyint(3) DEFAULT NULL,
  `SvSmBev12` tinyint(3) DEFAULT NULL,
  `Regdato21` date DEFAULT NULL,
  `AngiNRS21` tinyint(3) DEFAULT NULL,
  `StSmRo21` tinyint(3) DEFAULT NULL,
  `SvSmRo21` tinyint(3) DEFAULT NULL,
  `StSmBev21` tinyint(3) DEFAULT NULL,
  `SvSmBev21` tinyint(3) DEFAULT NULL,
  `SluttDato` date DEFAULT NULL,
  `Lege` tinyint(3) DEFAULT NULL,
  `AntTilsLege` smallint(6) DEFAULT NULL,
  `KonfLege` tinyint(3) DEFAULT NULL,
  `AntTilsKonfLege` smallint(6) DEFAULT NULL,
  `SykPleier` tinyint(3) DEFAULT NULL,
  `AntTilsSykPleier` smallint(6) DEFAULT NULL,
  `FysioT` tinyint(3) DEFAULT NULL,
  `AntTilsFysioT` smallint(6) DEFAULT NULL,
  `Psyk` tinyint(3) DEFAULT NULL,
  `AntTilsPsyk` smallint(6) DEFAULT NULL,
  `Sosio` tinyint(3) DEFAULT NULL,
  `AntTilsSosio` smallint(6) DEFAULT NULL,
  `AmbLege` tinyint(3) DEFAULT NULL,
  `AntTilsAmbLege` smallint(6) DEFAULT NULL,
  `AmbSykepleier` tinyint(3) DEFAULT NULL,
  `AntTilsAmbSpl` smallint(6) DEFAULT NULL,
  `AntPasTils` tinyint(3) DEFAULT NULL,
  `TotTid` smallint(6) DEFAULT NULL,
  `MedBeh22` tinyint(3) DEFAULT NULL,
  `Ingen1a` tinyint(3) DEFAULT NULL,
  `O2beh` tinyint(3) DEFAULT NULL,
  `Motgift1a` tinyint(3) DEFAULT NULL,
  `ForstOvervaakn` tinyint(3) DEFAULT NULL,
  `IntensivBeh` tinyint(3) DEFAULT NULL,
  `Resuc` tinyint(3) DEFAULT NULL,
  `RespiratorBeh` tinyint(3) DEFAULT NULL,
  `IkkeMedBeh` tinyint(3) DEFAULT NULL,
  `PSBeh` tinyint(3) DEFAULT NULL,
  `FysioBeh` tinyint(3) DEFAULT NULL,
  `AnnenIkkeMedBeh` tinyint(3) DEFAULT NULL,
  `SentralBlokk` tinyint(3) DEFAULT NULL,
  `EDA` tinyint(3) DEFAULT NULL,
  `SA` tinyint(3) DEFAULT NULL,
  `Opbehd221d` tinyint(3) DEFAULT NULL,
  `LAbehd221d` tinyint(3) DEFAULT NULL,
  `KoAbedel221d` tinyint(3) DEFAULT NULL,
  `Annetbehd221d` tinyint(3) DEFAULT NULL,
  `Kompl1d` tinyint(3) DEFAULT NULL,
  `ISEDHematom` tinyint(3) DEFAULT NULL,
  `Meningitt` tinyint(3) DEFAULT NULL,
  `EDabsc` tinyint(3) DEFAULT NULL,
  `NervSkad1d` tinyint(3) DEFAULT NULL,
  `MigKat` tinyint(3) DEFAULT NULL,
  `IvinjLA` tinyint(3) DEFAULT NULL,
  `PShodepine` tinyint(3) DEFAULT NULL,
  `FallpgaLA` tinyint(3) DEFAULT NULL,
  `LekCSF` tinyint(3) DEFAULT NULL,
  `Ingen1d` tinyint(3) DEFAULT NULL,
  `Operasjon1d` tinyint(3) DEFAULT NULL,
  `AbBeh1d` tinyint(3) DEFAULT NULL,
  `FjernKat1d` tinyint(3) DEFAULT NULL,
  `Bloodpatch` tinyint(3) DEFAULT NULL,
  `Sengeleie` tinyint(3) DEFAULT NULL,
  `FzKoff` tinyint(3) DEFAULT NULL,
  `EndrMed` tinyint(3) DEFAULT NULL,
  `PeriferBlokk` tinyint(3) DEFAULT NULL,
  `PlBrachBlok` tinyint(3) DEFAULT NULL,
  `Intersc` tinyint(3) DEFAULT NULL,
  `Supraclav` tinyint(3) DEFAULT NULL,
  `Infraklav` tinyint(3) DEFAULT NULL,
  `Axil` tinyint(3) DEFAULT NULL,
  `PVB` tinyint(3) DEFAULT NULL,
  `ICB` tinyint(3) DEFAULT NULL,
  `PECS` tinyint(3) DEFAULT NULL,
  `Underkat1` tinyint(3) DEFAULT NULL,
  `Underkat2` tinyint(3) DEFAULT NULL,
  `TAP` tinyint(3) DEFAULT NULL,
  `Femblok` tinyint(3) DEFAULT NULL,
  `AdKanalblok` tinyint(3) DEFAULT NULL,
  `Ischiasblok` tinyint(3) DEFAULT NULL,
  `Subglut` tinyint(3) DEFAULT NULL,
  `Popliteal` tinyint(3) DEFAULT NULL,
  `PLB` tinyint(3) DEFAULT NULL,
  `FICB` tinyint(3) DEFAULT NULL,
  `SPB` tinyint(3) DEFAULT NULL,
  `AnnenBlok` tinyint(3) DEFAULT NULL,
  `SShot` tinyint(3) DEFAULT NULL,
  `Infusjon` tinyint(3) DEFAULT NULL,
  `Kompl1e` tinyint(3) DEFAULT NULL,
  `NervSkad1e` tinyint(3) DEFAULT NULL,
  `Infeksjon1e` tinyint(3) DEFAULT NULL,
  `IvInjLA1e` tinyint(3) DEFAULT NULL,
  `Intox1e` tinyint(3) DEFAULT NULL,
  `Ingen1e` tinyint(3) DEFAULT NULL,
  `Op1e` tinyint(3) DEFAULT NULL,
  `AbBeh1e` tinyint(3) DEFAULT NULL,
  `FjernKat1e` tinyint(3) DEFAULT NULL,
  `EndretMedInt1e` tinyint(3) DEFAULT NULL,
  `VidereOppf` tinyint(3) DEFAULT NULL,
  `OppfanneInst` tinyint(3) DEFAULT NULL,
  `BehNedtrappAvsluttTils` tinyint(3) DEFAULT NULL,
  `Journalnotat` tinyint(3) DEFAULT NULL,
  `PlanLevertPas` tinyint(3) DEFAULT NULL,
  `UtdeltOpioidbrosjyre` tinyint(3) DEFAULT NULL,
  `OppfolgAvdeling` tinyint(3) DEFAULT NULL,
  `AarsakVedNei` tinyint(3) DEFAULT NULL,
  `KontFastlege` tinyint(3) DEFAULT NULL,
  `OppfSmeKl` tinyint(3) DEFAULT NULL,
  `IntKom22` varchar(2000) COLLATE utf8_danish_ci DEFAULT NULL,
  `FerdigSkjema22` tinyint(3) DEFAULT NULL,
  `Op22` tinyint(3) DEFAULT NULL,
  `NOp22` tinyint(3) DEFAULT NULL,
  `KoAn22` tinyint(3) DEFAULT NULL,
  `Bzd22` tinyint(3) DEFAULT NULL,
  `DDMoTbl22` decimal(5,1) DEFAULT NULL,
  `OMEQMoTbl22` decimal(6,1) DEFAULT NULL,
  `DDMoDep22` decimal(5,1) DEFAULT NULL,
  `OMEQMoDep22` decimal(6,1) DEFAULT NULL,
  `DDMoIV22` decimal(5,1) DEFAULT NULL,
  `OMEQMoIV22` decimal(6,1) DEFAULT NULL,
  `DDOxKps22` decimal(5,1) DEFAULT NULL,
  `OMEQOxKps22` decimal(6,1) DEFAULT NULL,
  `DDOxDep22` decimal(5,1) DEFAULT NULL,
  `OMEQOxDep22` decimal(6,1) DEFAULT NULL,
  `DDOxIV22` decimal(5,1) DEFAULT NULL,
  `OMEQOxIV22` decimal(6,1) DEFAULT NULL,
  `DDBuPl22` decimal(5,1) DEFAULT NULL,
  `OMEQBuPl22` decimal(7,1) DEFAULT NULL,
  `DDBuTbl22` decimal(5,1) DEFAULT NULL,
  `OMEQBuTbl22` decimal(7,1) DEFAULT NULL,
  `DDFePl22` decimal(5,1) DEFAULT NULL,
  `OMEQFePl22` decimal(7,1) DEFAULT NULL,
  `DDFeTblSpray22` decimal(5,1) DEFAULT NULL,
  `OMEQFeTblSpray22` decimal(7,1) DEFAULT NULL,
  `DDHyKps22` decimal(5,1) DEFAULT NULL,
  `OMEQHyKps22` decimal(7,1) DEFAULT NULL,
  `DDHyDepKps22` decimal(5,1) DEFAULT NULL,
  `OMEQHyDepKps22` decimal(7,1) DEFAULT NULL,
  `DDHyIv22` decimal(5,1) DEFAULT NULL,
  `OMEQHyIv22` decimal(7,1) DEFAULT NULL,
  `DDKeIV22` decimal(5,1) DEFAULT NULL,
  `OMEQKeIV22` decimal(7,1) DEFAULT NULL,
  `DDKeTbl22` decimal(5,1) DEFAULT NULL,
  `OMEQKeTbl22` decimal(7,1) DEFAULT NULL,
  `DDPeSupp22` decimal(5,1) DEFAULT NULL,
  `OMEQPeSupp22` decimal(7,1) DEFAULT NULL,
  `DDPeIM22` decimal(5,1) DEFAULT NULL,
  `OMEQPeIM22` decimal(7,1) DEFAULT NULL,
  `DDCoTbl22` decimal(5,1) DEFAULT NULL,
  `OMEQCoTbl22` decimal(7,1) DEFAULT NULL,
  `DDTrKps22` decimal(5,1) DEFAULT NULL,
  `OMEQTrKps22` decimal(7,1) DEFAULT NULL,
  `DDTrDepTbl22` decimal(5,1) DEFAULT NULL,
  `OMEQTrDepTbl22` decimal(7,1) DEFAULT NULL,
  `DDTaDepTbl22` decimal(5,1) DEFAULT NULL,
  `OMEQTaDepTbl22` decimal(7,1) DEFAULT NULL,
  `DDMetLav22` decimal(3,1) DEFAULT NULL,
  `OMEQMetLav22` decimal(7,1) DEFAULT NULL,
  `DDMetHoy22` decimal(4,1) DEFAULT NULL,
  `OMEQMetHoy22` decimal(7,1) DEFAULT NULL,
  `MoEkvivalens22` decimal(10,1) DEFAULT NULL,
  `AlvRespDepr` tinyint(3) DEFAULT NULL,
  `DatoUtfHADS` date DEFAULT NULL,
  `PasDelUtf` tinyint(3) DEFAULT NULL,
  `GrManglUtfylHADS` tinyint(3) DEFAULT NULL,
  `HADSSpm1` tinyint(3) DEFAULT NULL,
  `HADSSpm2` tinyint(3) DEFAULT NULL,
  `HADSSpm3` tinyint(3) DEFAULT NULL,
  `HADSSpm4` tinyint(3) DEFAULT NULL,
  `HADSSpm5` tinyint(3) DEFAULT NULL,
  `HADSSpm6` tinyint(3) DEFAULT NULL,
  `HADSSpm7` tinyint(3) DEFAULT NULL,
  `HADSSpm8` tinyint(3) DEFAULT NULL,
  `HADSSpm9` tinyint(3) DEFAULT NULL,
  `HADSSpm10` tinyint(3) DEFAULT NULL,
  `HADSSpm11` tinyint(3) DEFAULT NULL,
  `HADSSpm12` tinyint(3) DEFAULT NULL,
  `HADSSpm13` tinyint(3) DEFAULT NULL,
  `HADSSpm14` tinyint(3) DEFAULT NULL,
  `HADSScoreDepresjon` tinyint(3) DEFAULT NULL,
  `HADSScoreAngst` tinyint(3) DEFAULT NULL,
  `HenvistDato` date DEFAULT NULL,
  `Tilsynsanmodnin` tinyint(3) DEFAULT NULL,
  `TelefonCalling` tinyint(3) DEFAULT NULL,
  `StartdatoTO` date DEFAULT NULL,
  `Tilsett` tinyint(3) DEFAULT NULL,
  `Norsktalende` tinyint(3) DEFAULT NULL,
  `alder` smallint(6) DEFAULT NULL,
  `KognSvekket` tinyint(3) DEFAULT NULL,
  `InklKritOppf` tinyint(3) DEFAULT NULL,
  `SkriftligSamtyk` tinyint(3) DEFAULT NULL,
  `TypeManglSamt` tinyint(3) DEFAULT NULL,
  `DatoSamtykke` date DEFAULT NULL,
  `DatotrekSamt` date DEFAULT NULL,
  `DatoUtfylOpioid` date DEFAULT NULL,
  `PasdelUtfylOpioid` tinyint(3) DEFAULT NULL,
  `AarsakmanglUtfylOpioid` tinyint(3) DEFAULT NULL,
  `Utskrevetsykehus` tinyint(3) DEFAULT NULL,
  `Smstilletterutskrivelse` tinyint(3) DEFAULT NULL,
  `DolcontinMalfin` tinyint(3) DEFAULT NULL,
  `FentanylplDurogesicpl` tinyint(3) DEFAULT NULL,
  `Metadon` tinyint(3) DEFAULT NULL,
  `Morfin` tinyint(3) DEFAULT NULL,
  `Norspanplaster` tinyint(3) DEFAULT NULL,
  `OxyxontinReltebon` tinyint(3) DEFAULT NULL,
  `OxynormOxykodon` tinyint(3) DEFAULT NULL,
  `Palexia` tinyint(3) DEFAULT NULL,
  `PalladonHydromorfon` tinyint(3) DEFAULT NULL,
  `Paralginforte` tinyint(3) DEFAULT NULL,
  `Buprenorfin` tinyint(3) DEFAULT NULL,
  `Targiniq` tinyint(3) DEFAULT NULL,
  `Tramadolvarianter` tinyint(3) DEFAULT NULL,
  `Andre` tinyint(3) DEFAULT NULL,
  `Usikker` tinyint(3) DEFAULT NULL,
  `Fortsattbruk` tinyint(3) DEFAULT NULL,
  `InfoNedtrapping` tinyint(3) DEFAULT NULL,
  `HvemInfoNedtrapping` tinyint(3) DEFAULT NULL,
  `MuntligInfoNedtrapp` tinyint(3) DEFAULT NULL,
  `SkriftligNedtrappingsplan` tinyint(3) DEFAULT NULL,
  `InfoBrosjyreNedtrapp` tinyint(3) DEFAULT NULL,
  `FolgeAnbefalingNedtrapp` tinyint(3) DEFAULT NULL,
  `OpplevdAbstinenssympt` tinyint(3) DEFAULT NULL,
  `ForstodAbstinenssympt` tinyint(3) DEFAULT NULL,
  `LosningProblemAbstinens` tinyint(3) DEFAULT NULL,
  `OpplevdPlagsomTretthet` tinyint(3) DEFAULT NULL,
  `LosningProblemTretthet` tinyint(3) DEFAULT NULL,
  `InfoSmertestillBilkjoring` tinyint(3) DEFAULT NULL,
  `HvemInfoSmertestillBilkjoring` tinyint(3) DEFAULT NULL,
  `MuntligInfoBilkjoring` tinyint(3) DEFAULT NULL,
  `SkriftigInfoBilkjoring` tinyint(3) DEFAULT NULL,
  `InfoBrosyjreBilkjoring` tinyint(3) DEFAULT NULL,
  `HenvendelseAngSmertestill` tinyint(3) DEFAULT NULL,
  `InfoBrukNedtrapp` tinyint(3) DEFAULT NULL,
  `InfoSmstillBilkjoring` tinyint(3) DEFAULT NULL,
  `InfoAbstinenser` tinyint(3) DEFAULT NULL,
  `InfoBivirkninger` tinyint(3) DEFAULT NULL,
  `TettOppfolging` tinyint(3) DEFAULT NULL,
  `DatoinhOppl` date DEFAULT NULL,
  `Fdato` date DEFAULT NULL,
  `Kjonn` tinyint(3) DEFAULT NULL,
  `SkrSamtykke` tinyint(3) DEFAULT NULL,
  `DatoinhSamt` date DEFAULT NULL,
  `ManglSamt` tinyint(3) DEFAULT NULL,
  `DatoTrektSamt` date DEFAULT NULL,
  `Avdod` tinyint(3) DEFAULT NULL,
  `Ddato` date DEFAULT NULL,
  `Adrtype` tinyint(3) DEFAULT NULL,
  `DatoUfylEval` date DEFAULT NULL,
  `PasdelUtfylEval` tinyint(3) DEFAULT NULL,
  `AarsakmanglUfylEval` tinyint(3) DEFAULT NULL,
  `HuskerSmerteteam` tinyint(3) DEFAULT NULL,
  `EvalSpm1` tinyint(3) DEFAULT NULL,
  `EvalSpm2` tinyint(3) DEFAULT NULL,
  `EvalSpm3` tinyint(3) DEFAULT NULL,
  `EvalSpm4` tinyint(3) DEFAULT NULL,
  `EvalSpm5` tinyint(3) DEFAULT NULL,
  `EvalSpm6` tinyint(3) DEFAULT NULL,
  `EvalSpm7` tinyint(3) DEFAULT NULL,
  `EvalSpm8` tinyint(3) DEFAULT NULL,
  `EvalSpm9` tinyint(3) DEFAULT NULL,
  `EvalSpm10` tinyint(3) DEFAULT NULL,
  `EvalSpm11` tinyint(3) DEFAULT NULL,
  `DatoUfylPR` date DEFAULT NULL,
  `PasDelUfylPR` tinyint(3) DEFAULT NULL,
  `GrunnManglUtfyl` tinyint(3) DEFAULT NULL,
  `PRSpm1` tinyint(3) DEFAULT NULL,
  `PRSpm2` tinyint(3) DEFAULT NULL,
  `PRSpm3` tinyint(3) DEFAULT NULL,
  `PRSpm3Mangler` tinyint(3) DEFAULT NULL,
  `PRSpm4` tinyint(3) DEFAULT NULL,
  `PRSpm5` tinyint(3) DEFAULT NULL,
  `PRSpm6` tinyint(3) DEFAULT NULL,
  PRIMARY KEY (`ForlopsID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_danish_ci;


DROP TABLE IF EXISTS `avdelingsoversikt`;
CREATE TABLE `avdelingsoversikt` (
  `DEPARTMENT_ID` int(9) NOT NULL,
  `DEPARTMENT_CENTREID` varchar(30) COLLATE utf8_danish_ci DEFAULT NULL,
  `DEPARTMENT_NAME` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `DEPARTMENT_SHORTNAME` varchar(20) COLLATE utf8_danish_ci DEFAULT NULL,
  `DEPARTMENT_RESH` varchar(10) COLLATE utf8_danish_ci DEFAULT NULL,
  `DEPARTMENT_ACTIVE` tinyint(3) DEFAULT NULL,
  `LOCATION_ID` int(10) unsigned DEFAULT NULL,
  `LOCATION_CENTREID` varchar(30) COLLATE utf8_danish_ci DEFAULT NULL,
  `LOCATIONNAME` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `LOCATION_SHORTNAME` varchar(20) COLLATE utf8_danish_ci DEFAULT NULL,
  `LOCATION_ACTIVE` tinyint(3) DEFAULT NULL,
  PRIMARY KEY (`DEPARTMENT_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_danish_ci;


DROP TABLE IF EXISTS `forlopsoversikt`;
CREATE TABLE `forlopsoversikt` (
  `AvdRESH` varchar(30) COLLATE utf8_danish_ci DEFAULT NULL,
  `SykehusNavn` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `PasientID` varchar(10) COLLATE utf8_danish_ci DEFAULT NULL,
  `PostNr` varchar(4) COLLATE utf8_danish_ci DEFAULT NULL,
  `PostSted` varchar(50) COLLATE utf8_danish_ci DEFAULT NULL,
  `Kommune` varchar(50) COLLATE utf8_danish_ci DEFAULT NULL,
  `Kommunenr` varchar(4) COLLATE utf8_danish_ci DEFAULT NULL,
  `Fylke` varchar(50) COLLATE utf8_danish_ci DEFAULT NULL,
  `Fylkenr` varchar(2) COLLATE utf8_danish_ci DEFAULT NULL,
  `KryptertFnr` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `PasientKjonn` varchar(13) COLLATE utf8_danish_ci DEFAULT NULL,
  `erMann` varchar(1) COLLATE utf8_danish_ci DEFAULT NULL,
  `PasientAlder` decimal(12,4) DEFAULT NULL,
  `Fodselsdato` date DEFAULT NULL,
  `Norsktalende` varchar(10) COLLATE utf8_danish_ci DEFAULT NULL,
  `Sivilstatus` varchar(30) COLLATE utf8_danish_ci DEFAULT NULL,
  `UtdanningSSB` varchar(50) COLLATE utf8_danish_ci DEFAULT NULL,
  `Avdod` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `AvdodDato` date DEFAULT NULL,
  `ForlopsID` varchar(10) COLLATE utf8_danish_ci NOT NULL,
  `BasisRegStatus` varchar(2) COLLATE utf8_danish_ci DEFAULT NULL,
  `ForlopsType1` varchar(24) COLLATE utf8_danish_ci DEFAULT NULL,
  `ForlopsType1Num` varchar(2) COLLATE utf8_danish_ci DEFAULT NULL,
  `ForlopsType2` varchar(16) COLLATE utf8_danish_ci DEFAULT NULL,
  `ForlopsType2Num` varchar(1) COLLATE utf8_danish_ci DEFAULT NULL,
  `HovedDato` date DEFAULT NULL,
  `KobletForlopsID` varchar(10) COLLATE utf8_danish_ci DEFAULT NULL,
  `OppflgRegStatus` varchar(2) COLLATE utf8_danish_ci DEFAULT NULL,
  `ErOppflg` varchar(1) COLLATE utf8_danish_ci DEFAULT NULL,
  `OppflgStatus` varchar(30) COLLATE utf8_danish_ci DEFAULT NULL,
  `OppflgSekNr` varchar(6) COLLATE utf8_danish_ci DEFAULT NULL,
  PRIMARY KEY (`ForlopsID`),
  KEY `idx_forlopsoversikt` (`AvdRESH`,`HovedDato`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_danish_ci;


DROP TABLE IF EXISTS `skjemaoversikt`;
CREATE TABLE `skjemaoversikt` (
  `Skjemanavn` varchar(20) COLLATE utf8_danish_ci NOT NULL,
  `SkjemaStatus` varchar(3) COLLATE utf8_danish_ci DEFAULT NULL,
  `ForlopsID` varchar(10) COLLATE utf8_danish_ci NOT NULL,
  `OpprettetAv` varchar(30) COLLATE utf8_danish_ci DEFAULT NULL,
  `OpprettetDato` timestamp NULL DEFAULT NULL,
  `SistLagretAv` varchar(30) COLLATE utf8_danish_ci DEFAULT NULL,
  `SistLagretDato` timestamp NULL DEFAULT NULL,
  `Sykehusnavn` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `HovedDato` date DEFAULT NULL,
  `AvdRESH` varchar(30) COLLATE utf8_danish_ci DEFAULT NULL,
  `SkjemaRekkeflg` varchar(2) COLLATE utf8_danish_ci DEFAULT NULL,
  PRIMARY KEY (`ForlopsID`,`Skjemanavn`),
  KEY `idx_skjemaoversikt` (`AvdRESH`,`HovedDato`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_danish_ci;


DROP TABLE IF EXISTS `smertediagnoser`;
CREATE TABLE `smertediagnoser` (
  `SmerteDiagID` int(9) NOT NULL,
  `ForlopsID` int(10) unsigned DEFAULT NULL,
  `SmerteKat` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `DiagKat` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `DiagSubKat` varchar(255) COLLATE utf8_danish_ci DEFAULT NULL,
  `ICD10Kode` varchar(10) COLLATE utf8_danish_ci DEFAULT NULL,
  `ICD10Tekst` varchar(200) COLLATE utf8_danish_ci DEFAULT NULL,
  `ICD10Versjon` int(10) unsigned DEFAULT NULL,
  `HovedDiag` varchar(100) COLLATE utf8_danish_ci DEFAULT NULL,
  `OpprettetAv` varchar(30) COLLATE utf8_danish_ci DEFAULT NULL,
  PRIMARY KEY (`SmerteDiagID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_danish_ci;


DROP TABLE IF EXISTS `smertediagnosernum`;
CREATE TABLE `smertediagnosernum` (
  `SmerteDiagID` int(9) NOT NULL,
  `ForlopsID` int(10) unsigned DEFAULT NULL,
  `SmerteKat` tinyint(3) DEFAULT NULL,
  `DiagKat` tinyint(3) DEFAULT NULL,
  `DiagSubKat` tinyint(3) DEFAULT NULL,
  `ICD10Kode` varchar(10) COLLATE utf8_danish_ci DEFAULT NULL,
  `ICD10Tekst` varchar(200) COLLATE utf8_danish_ci DEFAULT NULL,
  `ICD10Versjon` int(10) unsigned DEFAULT NULL,
  `PAINMAINDIAG` tinyint(3) DEFAULT NULL,
  `OpprettetAv` varchar(30) COLLATE utf8_danish_ci DEFAULT NULL,
  PRIMARY KEY (`SmerteDiagID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_danish_ci;
