---
params:
  title: 'Tid til død etter utskrivelse'
  author: 'Rapporteket'
  hospitalName: 'Ukjent sykehus'
  reshId: 'locallyDefined'
  userRole: 'MyRole'
  userFullName: 'Ukjent bruker'
  startDate: !r lubridate::today() - lubridate::years(1)
  endDate: !r lubridate::today() - lubridate::weeks(1)
  year: '2016'
  tableFormat: 'html'
  registryName: 'rapbase'
  shinySession: list()
title: '`r paste(params$title, params$hospitalName, " i perioden fra ", params$startDate, " til ", params$endDate)`'
author: '`r params$author`'
date: '`r format(Sys.time(), "%d\\. %B, %Y")`'
reglogo: '`r system.file("www/logoSmerte.png", package = "smerte")`'
regtext: '`r readLines(system.file("registryShortDescription.txt", package = "smerte"))`'
registryName: Smerteregisteret
userFullName: '`r params$userFullName`'
---
```{r set options and load packages, include = FALSE}
knitr::opts_chunk$set(echo=FALSE)
options(knitr.table.format = params$tableFormat)
options(tinytex.verbose = TRUE)

library(lubridate)
library(tidyverse)
library(ggplot2)
```

```{r get data, include=FALSE}

if (rapbase::isRapContext()) {
  fulldat <- smerte::getRegDataTimetodeath(
    registryName = params$registryName,
    reshId = params$reshId,
    userRole = params$userRole,
    startDate = params$startDate,
    endDate = params$endDate,
    session = params$shinySession
  )
} else {
  
  #Dataimport: skal hente lokale data for hvert sykehus (tar vekk sti, og erstatter med lokal fil)
  
  #AlleVarNum
  path <- read.csv(file = "H:/path.csv", header = FALSE, sep = ";")
  path <- as.data.frame(lapply(path, as.character), stringsAsFactors=FALSE)
  path <- path$V1
  dat <- read.csv(file = path, header = TRUE, sep = ";")
  
  #Diagnosefil numerisk
  pathd <- read.csv(file = "H:/pathdiag.csv", header = FALSE, sep = ";")
  pathd <- as.data.frame(lapply(pathd, as.character), stringsAsFactors=FALSE)
  pathd <- pathd$V1
  diagnum <- read.csv(file = pathd, header = TRUE, sep = ";")
  
  #Diagnosefil
  pathdt <- read.csv(file = "H:/pathdiagtekst.csv", header = FALSE, sep = ";", encoding = "UTF-8")
  pathdt <- as.data.frame(lapply(pathdt, as.character), stringsAsFactors=FALSE)
  pathdt <- pathdt$V1
  diag <- read.csv(file = pathdt, header = TRUE, sep = ";", encoding = "UTF-8")
  
  #Joiner diagnose numerisk og diagnosetekst
  diagfull = diagnum %>% left_join(diag, by = c("ForlopsID", "HovedDato", "SmerteDiagID"))
  #Joiner så AlleVarNum med diagnose_full
  fulldat = left_join(dat, diagfull, by = "ForlopsID")
  
}

#Funksjon som skal evaluere om dataframe er tom eller ikke
dataPresent <- TRUE
if(dim(fulldat)[1] < 1) {
  dataPresent <- FALSE
}
```



```{r noData, eval=!dataPresent, results='asis'}
cat('# Upps...\nI den valgte tidsperioden er det ikke nok data til å gi 
    ut resultater.')
knitr::knit_exit()

```


```{r datawrangl, eval=dataPresent, include = FALSE}
#Sluttdato mangler noen, men tror det blir riktig
fulldat$enddate <- as.Date(fulldat$SluttDato)
fulldat$deathd <- as.Date(fulldat$Ddato)

#Only those who were seen (and changing name from fulldat to dat)
dat <- fulldat %>%
  filter(Tilsett == 1)

#Finner uker mellom utskrivelse og eventuell død
dat$diff <- difftime(dat$deathd, dat$enddate, units = "weeks")

#Lager variabel timeafter som kategorieserer inn i måneder av ulik lengde
dat <- dat %>% 
  mutate(timeafter = 
                case_when(diff <= 4 ~ 'Innen 1 måned',
                          diff > 4 & diff <= 12 ~ '1-3 måneder',
                          diff > 12 & diff <= 24 ~ '3-6 måneder',
                          diff > 24 & diff <= 52 ~'6-12 måneder',
                          diff > 52 ~ 'Over 1 år'))

#Gjør til faktor med riktig levels
dat$timeafter <- factor(dat$timeafter, 
                        levels = c("Innen 1 måned", "1-3 måneder",
                                   "3-6 måneder", "6-12 måneder", "Over 1 år"))


#Creating data set with only those who died
datd <- dat %>%
  filter(!is.na(dat$timeafter))

```

Figuren viser hvor fordelingen over hvor lang tid det var fra sluttdato (registert i registeret) til dødsdato. Overlevende vises ikke her.
```{r barplot, eval=dataPresent, results='asis'}

ggplot(datd, aes(x = timeafter)) +
  geom_bar(stat="count", width=0.7, fill="steelblue") +
  scale_x_discrete(name ="Tid til død etter sluttføring") +
  scale_y_continuous(name = "Antall") +
  theme_minimal() +
  theme(text = element_text(size = 15)) 
```
