---
params:
  title: ': Variabeloversikt'
  author: 'Rapporteket'
  hospitalName: 'Ukjent sykehus'
  reshId: 'locallyDefined'
  avdValg: 'Nasjonalt'
  Data: NA
  userRole: 'MyRole'
  userFullName: 'Ukjent bruker'
  startDate: !r lubridate::today() - lubridate::years(1)
  endDate: !r lubridate::today() - lubridate::weeks(1)
  year: '2016'
  tableFormat: 'html'
  registryName: 'rapbase'
  shinySession: list()
title: '`r paste0("Smerteregisteret ", params$hospitalName, params$title)`'
author: '`r params$author`'
date: '`r format(Sys.time(), "%d\\. %B, %Y")`'
reglogo: '`r system.file("www/logoSmerte.png", package = "smerte")`'
regtext: 'SmerteReg er et nasjonalt kvalitetsregister som registrer alleinneliggende pasienter som henvises for tilsyn fra akutt smerteteam. Formålet med SmerteReg er å bedre kvaliteten på tjenesten akutt smerteteam yter til smertepasienter på norske sykehus samt å danne grunnlag for forskning.'
registryName: Smerteregisteret
userFullName: '`r params$userFullName`'
---

```{r set options and load packages, include = FALSE}
knitr::opts_chunk$set(echo=FALSE)
options(knitr.table.format = params$tableFormat)
options(tinytex.verbose = TRUE)
options(scipen = 1, digits = 2) #set to two decimal 

```

```{r get-data, warning = FALSE, message=TRUE}

 if (rapbase::isRapContext()) {
   
   dat <- smerte::GetRegDataVariabeloversikt(registryName = params$registryName,
                                        tableName = "AlleVarNum",
                                        reshId = params$reshId,
                                        userRole=params$userRole,
                                        startDate = params$startDate,
                                        endDate = params$endDate,
                                        session = params$shinySession)
 } else { print("fikk ikke inn data")}

  if(params$avdValg == "Nasjonalt") {
    dat_variabeloversikt = dat
  } else{
    dat_variabeloversikt = dat %>% 
      dplyr::filter(SykehusNavn == params$avdValg)
  }


#Forkorter sykehusnavn
# dat$SykehusNavn_kort[dat$SykehusNavn == "Universitetssykehuset Nord-Norge HF"] = "UNN"
# dat$SykehusNavn_kort[dat$SykehusNavn == "St. Olavs Hospital HF"] = "St. Olavs"
# dat$SykehusNavn_kort[dat$SykehusNavn == "Oslo universitetssykehus HF"] = "OUS"
# dat$SykehusNavn_kort[dat$SykehusNavn == "Oslo universitetssykehus HF / Smerteteam, RH"] = "OUS, RH"
# dat$SykehusNavn_kort[dat$SykehusNavn == "Oslo universitetssykehus HF / Smerteteam, UL"] = "OUS, UL"
# dat$SykehusNavn_kort[dat$SykehusNavn == "Helse Bergen HF"] = "HB"
# dat$SykehusNavn_kort[dat$SykehusNavn == "Helse Møre og Romsdal HF"] = "HMR"
# dat$SykehusNavn_kort[dat$SykehusNavn == "Vestre Viken HF"] = "VV"
# dat$SykehusNavn_kort[dat$SykehusNavn == "Vestre Viken HF / Klinikk Bærum Sykehus"] = "VV, Bærum"
# dat$SykehusNavn_kort[dat$SykehusNavn == "Akershus universitetssykehus HF"] = "AHUS"


#Legger inn månedene i riktig rekkefølge
# dat <- dat %>%
#   dplyr::mutate(monthname = zoo::as.Date(zoo::as.yearmon(StartdatoTO)))

```

# Variabeloversikt - `r params$avdValg`

Datagrunnlag: `r params$avdValg`   <br>
StartDato:    `r params$startDate` <br>
SluttDato:    `r params$endDate`

```{r, vaske-data, echo = FALSE}

# variabler av liten interesse
  vars_drop = c("AvdRESH", "SykehusNavn", "ForlopsID", 
                "PasientID")

dat_rapport = dat_variabeloversikt %>% 
  dplyr::select(-vars_drop) %>% 
  janitor::remove_constant() %>% 
  janitor::remove_empty("cols")
  
```


```{r, fig-fordeling, eval = FALSE}

fig_fordeling = DataExplorer::plot_intro(dat_rapport, 
                                         ggtheme = ggplot2::theme_minimal())
```

```{r, fig-missing, fig.height=20, eval=FALSE}
fig_missing = DataExplorer::plot_missing(dat_rapport,
                                         missing_only = TRUE,
                                         ggtheme = ggplot2::theme_minimal(), 
                                         title = "Andel manglende registreringer")
```

# Fordeling av diskrete verdier
```{r, fig-bars, eval=TRUE, echo = FALSE, message=FALSE}
fig_bars = DataExplorer::plot_bar(dat_rapport, 
                                  ggtheme = ggplot2::theme_minimal(),
                                  nrow = 3,
                                  ncol = 2)
```

# Fordeling av kontinuerlige verdier
```{r, fig-hist, eval = TRUE}
fig_hist = DataExplorer::plot_histogram(dat_rapport, 
                                        ggtheme = ggplot2::theme_minimal(), 
                                        nrow = 3, 
                                        ncol = 2)
```

