---
title: 'Forside'
author: ''
date: '`r format(Sys.time(), "%d. %B %Y")`'
output: 
  html_document: 
    keep_md: yes
---

# Smerteregisteret i Rapporteket
Dette er Smerteregisterets egen side, hvor man finner informasjon og rapporter knyttet til lokale og nasjonale data. Videre følger en forklaring på hva som finnes på rapporteket og hvordan det kan brukes.

# Rapporter og data
Her finnes rapportene det er mulig å hente ut fra rapporteket. Etter hvert som nye rapporter lages vil de legges til i nedtrekksmenyen _Rapporter_ øverst på siden. Dersom det er ønskelig ønsker å få tilsendt en rapport fast (f.eks. månedlig) kan dette bestilles under fanen _Abonnement_. Alle registerets datadumper kan hentes ned under fanen _Datadump_. Hvis man er innlogget via lokalt sykehus, vil rapportene generes med lokale data for dette sykehuset. Er man innlogget på det nasjonale registeret brukes nasjonale data.

## Registerets nåværende rapporter

**Tilsyn:** informasjon om henvisninger, tilsyn (fordelt på lege, sykepleier etc.) og avdelingsoversikt for lokale data.

**Dekningsgrad før reservasjon:** utregning av dekningsgrad over valgfri tidsperiode for lokale data (gjelder før reservasjonsrett/til desember 2022).

**Dekningsgrad etter reservasjon:** utregning av dekningsgrad over valgfri tidsperiode for lokale data (gjelder etter reservasjonsrett/fra desember 2022).

**Indikatorer:** Smerteregisterets resultat - og kvalitetsindikatorer for lokale eller nasjonale data. I tillegg ligger informasjon rundt NRS for kvalitetsforbedringsprosjektet her.

**ePROM:** oversikt over alle variablene i alle eprom-skjema for lokale eller nasjonale data.

**Spinalkateter:** diverse informasjon om de pasientene som har fått spinalkateter (tilsyn, morfinekvivalenter, NRS m.m.) for lokale data.

**Smertekategori:** oversikt over hovedsmertekategori, undersmertekategorier og opioidbruk ved innleggelse for lokale data.

**Opioidreduksjon:** oversikt over nedgang i morfinekvivalenter.

**Epidural (barn):** oversikt antall barn som fikk epidural og aldersfordeling blant disse.

**Oppfølging ved smerteklinikk:** lokal avdelingsoversikt over anbefalt oppfølging ved smerteklinikk.

**Tid til død etter utskrivelse:** oversikt inkludert fordeling blant de ulike smertekategoriene (hoved).

# Nye rapporter
Dersom det er informasjon som er av interesse å hente ut gjentatte ganger kan det lønne seg å få laget en rapport. 

En forespørsel om ny rapport kan sendes til janne.mannseth@helse-bergen.no. Beskriv nøye hva som ønskes. Det vil f.eks. være hvilke variabler som trengs, om resultatene skal vises totalt eller gruppevis og om en spesiell type visualisering som er ønskelig.
 
