on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

name: test-coverage

jobs:
  test-coverage:
    runs-on: ubuntu-20.04
    env:
      GITHUB_PAT: ${{ secrets.GT }}
      GITHUB_ACTIONS_RUN_DB_UNIT_TESTS: true
      DB_HOST: "localhost"
      DB_USER: "root"
      DB_PASS: "root"
    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-r@v2

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::covr, any::xml2
          needs: coverage
  
      - uses: r-lib/actions/setup-pandoc@v2
      - uses: r-lib/actions/setup-tinytex@v2

      - name: Install system dependencies
        run: |
          sudo apt-get install libcurl4-openssl-dev

      - name: Set up MySQL, ubuntu only
        run: |
          sudo /etc/init.d/mysql start
          mysql -e 'CREATE DATABASE IF NOT EXISTS testdb;' -uroot -proot

      - name: Test coverage
        run: covr::codecov()
        shell: Rscript {0}
