on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

name: test-coverage

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  test-coverage:
    runs-on: ubuntu-24.04
    env:
      GITHUB_PAT: ${{ secrets.GH_TOKEN }}
      GITHUB_ACTIONS_RUN_DB_UNIT_TESTS: true
      MYSQL_HOST: "localhost"
      MYSQL_USER: "root"
      MYSQL_PASSWORD: "root"
      MYSQL_DB_DATA: "testdb"
    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-r@v2

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::covr, any::xml2
          needs: coverage

      - uses: r-lib/actions/setup-pandoc@v2
      - uses: r-lib/actions/setup-tinytex@v2
      - name: Set up MySQL, ubuntu only
        run: |
          sudo apt-get update
          sudo apt-get install -y mysql-server
          sudo service mysql start
          mysql -e 'CREATE DATABASE IF NOT EXISTS testdb;' -uroot -proot

      - name: Test coverage
        run: covr::codecov(token = "${{ secrets.CODECOV_TOKEN }}")
        shell: Rscript {0}
      - name: Upload testthat output if tests fail
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: testthat-output
          path: /tmp/Rtmp*/R_LIBS*/smerte/smerte-tests
      - name: List test output files
        if: failure()
        run: |
          ls -lR /tmp/Rtmp*/R_LIBS*/smerte
